project_id = "rwzpffsaivgjuuthvkfa"

[functions.job-webhook]
verify_jwt = false

[functions.process-case-files]
verify_jwt = true

[functions.initial-parse-files]
verify_jwt = true

[functions.final-analysis-files]
verify_jwt = true

[functions.send-contact-email]
verify_jwt = false

[functions.send-support-ticket]
verify_jwt = true