project_id = "rwzpffsaivgjuuthvkfa"

[functions.job-webhook]
verify_jwt = false

[functions.process-case-files]
verify_jwt = true

[functions.initial-parse-files]
verify_jwt = true

[functions.final-analysis-files]
verify_jwt = true

[functions.send-contact-email]
verify_jwt = false

[functions.send-support-ticket]
verify_jwt = true

[functions.runtime-config]
verify_jwt = false

[functions.admin-get-users]
verify_jwt = true

[functions.grant-subscription]
verify_jwt = true

[functions.revoke-subscription]
verify_jwt = true

[functions.send-subscription-email]
verify_jwt = false

[functions.check-expired-subscriptions]
verify_jwt = false

[functions.bootstrap-admin]
verify_jwt = true

[functions.admin-get-all-cases]
verify_jwt = true